# Generated by Django 2.1.7 on 2020-03-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
